# Uncomment the next line to define a global platform for your project
# platform :ios, ‘8.0’

platform :ios, '9.0'
use_frameworks!

target 'MGAssociationMenuView-Demo' do
   pod 'SnapKit'

  # Pods for MGAssociationMenuView-Demo

  target 'MGAssociationMenuView-DemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MGAssociationMenuView-DemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
